version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: rssdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  feed_fetcher:
    build: ./feed_fetcher
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/rssdb

  ai_processing:
    build: ./ai_processing
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/rssdb

  web_application:
    build: ./api
    depends_on:
      - database
      - ai_processing
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@database:5432/rssdb

volumes:
  db_data:
